# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-users:5432/usuarios_db
spring.datasource.username=karen
spring.datasource.password=2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8084

# SMTP Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=90ad77001@smtp-brevo.com
spring.mail.password=2QV0mR5tv0BbSXlh

# Seguridad SMTP
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.test-connection=true
