spring.datasource.url=jdbc:postgresql://postgres-login:5432/usuarios_db
spring.datasource.username=karen
spring.datasource.password=2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083