spring.datasource.url=jdbc:postgresql://postgres-users:5432/usuarios_db
spring.datasource.username=karen
spring.datasource.password=2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.data.redis.host=redis
#spring.data.redis.port=6379
#server.port=8080