server {
    listen 80;

    # DOMINIO: USERS
    location /api/users/login {
        proxy_pass http://login-service-full:8080/login;
    }

    location /api/users/register {
        proxy_pass http://registration-service:8082/register;
    }

    location /api/users/reset {
        proxy_pass http://reset-password-service:8083/reset-password;
    }

   location /api/users/verify-email {
    proxy_pass http://verify-email-service:8084/verify-email;
    }
  


# DOMINIO: REGISTRO
    location /api/registro/verify-session {
        proxy_pass http://verify-session-service:8097;
    }

    location /api/registro/expire-session {
        proxy_pass http://expire-session-service:8099;
    }

    location /api/registro/log-error {
        proxy_pass http://log-error-service:8100;
    }

    # DOMINIO: ACCOUNTS
    location /api/cuentas/create {
        proxy_pass http://create-account-service:8085;
    }

    location /api/cuentas/get {
        proxy_pass http://get-account-service:8086;
    }

    location /api/cuentas/close {
        proxy_pass http://close-account-service:8087;
    }

    location /api/cuentas/validate {
        proxy_pass http://validate-account-service:8088;
    }

    # DOMINIO: MOVEMENTS
    location /api/movimientos/deposit {
        proxy_pass http://deposit-service:8089;
    }

    location /api/movimientos/transfer {
        proxy_pass http://transfer-service:8090;
    }

    location /api/movimientos/withdraw {
        proxy_pass http://withdraw-service:8094;
    }

    location /api/movimientos/history {
        proxy_pass http://transaction-history-service:8091;
    }

    location /api/movimientos/get {
        proxy_pass http://get-transaction-service:8092;
    }
    
    location /api/movimientos/alerts {
        proxy_pass http://alerts-service:8093;
    }

    # DOMINIO: NOTIFICATIONS
    location /api/notificaciones/email {
        proxy_pass http://send-email-service:8095;
    }

    location /api/notificaciones/sms {
        proxy_pass http://send-sms-service:8096;
    }

    

    # DOMINIO: CONFIG / EXCHANGE
    location /api/divisas/exchange-rate {
        proxy_pass http://exchange-rate-service:8098;
    }

    
}
